### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by fpsapc** [fpsapc/reactreduxgroupproject#25]
Hello Reviewer,
- We setup our Kanban board for React & Redux group project
- We are three members of this project. here is the link of project
- https://github.com/fpsapc/reactreduxgroupproject/projects/1

**Comment by DuaneDave** [comment]
Hi @fpsapc, @Ellyboi and @Mylo16 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Tasks are correctly assigned to members of the team
✔️ Kanban is set up as expected

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fpsapc** [comment]
Thanks

**Comment by Ellyboi** [comment]
Thanks
